// 365-Day Trading Curriculum for COMMAND. OS
// One unique lesson per day of the year

export const TRADING_CURRICULUM: string[] = [
  // FOUNDATIONS (Days 1-30)
  "Day 1: Markets exist to transfer money from impatient people to patient ones. Master patience first.",
  "Day 2: The bid-ask spread is the market maker's cut. Always account for it in your calculations.",
  "Day 3: Support levels are price zones where buyers historically overwhelm sellers. Mark them on your chart.",
  "Day 4: Resistance levels are price zones where sellers historically overwhelm buyers. They become support when broken.",
  "Day 5: A candlestick's body shows the open-to-close range. Long body = strong conviction.",
  "Day 6: A doji candle means indecision — neither buyers nor sellers won. Watch what happens next.",
  "Day 7: The hammer candle signals a rejection of lower prices. Strongest when it appears at support.",
  "Day 8: Never risk more than 1% of your total account on a single trade. This is non-negotiable.",
  "Day 9: Risk-reward ratio should be at minimum 1:2. If you risk $50, you must target $100 profit.",
  "Day 10: Cutting losses quickly is a skill. Being right about direction is secondary to managing risk.",
  "Day 11: Volume confirms price moves. A breakout on LOW volume is very likely to fail.",
  "Day 12: The trend is your friend until it ends. Trading against the trend requires precise timing.",
  "Day 13: Higher highs and higher lows define an uptrend. Lower highs and lower lows define a downtrend.",
  "Day 14: Moving averages smooth price action. The 20 EMA is a reliable short-term trend indicator.",
  "Day 15: When price is above the 200-day MA, the market is in a long-term bull structure.",
  "Day 16: A golden cross (50 MA crossing above 200 MA) signals bullish momentum shifts.",
  "Day 17: A death cross (50 MA crossing below 200 MA) signals bearish momentum shifts.",
  "Day 18: RSI below 30 suggests oversold conditions. RSI above 70 suggests overbought conditions.",
  "Day 19: MACD crossovers confirm momentum changes but always lag — never use alone.",
  "Day 20: Bollinger Bands squeeze before explosive moves. Watch for a breakout from the squeeze.",
  "Day 21: Fibonacci retracements (38.2%, 50%, 61.8%) are key pullback zones in a trending market.",
  "Day 22: The 61.8% Fib level is called 'the golden ratio'. Price often reverses precisely here.",
  "Day 23: ATR (Average True Range) tells you how volatile an asset is. Size your trades accordingly.",
  "Day 24: Liquidity is king. Avoid trading illiquid markets where your order moves the price.",
  "Day 25: Pre-market and after-hours moves are less reliable. Most volume is during market hours.",
  "Day 26: News drives emotion. Fade the news when the technical picture conflicts.",
  "Day 27: The first move after major news is almost always a trap. Let the dust settle.",
  "Day 28: Paper trade any new strategy for at least 50 trades before risking real capital.",
  "Day 29: Journal every trade: entry, exit, reason, emotion. Review weekly without exception.",
  "Day 30: After 30 days, audit your journal. What was your biggest mistake? Fix that one thing.",
  // CHART PATTERNS (Days 31-60)
  "Day 31: A bull flag is a sharp upward move followed by a tight sideways consolidation. Buy the breakout.",
  "Day 32: A bear flag is a sharp downward move followed by a tight sideways rally. Sell the breakdown.",
  "Day 33: A cup and handle pattern signals continuation of an uptrend after a rounded consolidation.",
  "Day 34: A head and shoulders pattern is one of the most reliable reversal signals in technical analysis.",
  "Day 35: An inverse head and shoulders signals a bullish reversal from a downtrend.",
  "Day 36: Double tops are bearish reversals. Price tests a high twice and fails — then falls hard.",
  "Day 37: Double bottoms are bullish reversals. Price tests a low twice and holds — then rallies.",
  "Day 38: Ascending triangles break upward. Descending triangles break downward — usually.",
  "Day 39: Symmetrical triangles can break either direction. Wait for the actual breakout before trading.",
  "Day 40: A wedge pattern against the trend is a powerful continuation signal for the main trend.",
  "Day 41: Gaps on charts represent absent trading. Island reversals (gaps both sides) are extreme signals.",
  "Day 42: The three white soldiers pattern is three consecutive bullish candles. Strong buying pressure.",
  "Day 43: The three black crows is three consecutive bearish candles. Strong selling pressure.",
  "Day 44: A morning star is a three-candle bullish reversal. Large bear candle, doji, large bull candle.",
  "Day 45: An evening star is a three-candle bearish reversal at the top of an uptrend.",
  "Day 46: Engulfing candles are powerful. A bullish engulfing candle consumes the prior red candle entirely.",
  "Day 47: Chart patterns take time to form. A pattern that forms in 1 hour is less reliable than one in 1 week.",
  "Day 48: The longer the base before a breakout, the more powerful the move. 'The bigger the base, the stronger the case.'",
  "Day 49: Always zoom out before trading. The daily trend trumps the 5-minute chart pattern.",
  "Day 50: Confluence of patterns (Fib + support + trend line) creates the highest probability trades.",
  "Day 51: Draw trend lines using wicks, not closes. Price wicks represent real market tests of a level.",
  "Day 52: A channel is two parallel trend lines. Buy the bottom, sell the top — or trade the breakout.",
  "Day 53: Range-bound markets are choppy. Wait for a clean breakout before directional bias.",
  "Day 54: The open and close of each daily candle are the most important prices of that session.",
  "Day 55: Point of control (POC) in volume profile is where most trading happened. Price gravitates here.",
  "Day 56: High volume nodes are areas of strong support or resistance in a volume profile.",
  "Day 57: Low volume nodes are thin areas price cuts through quickly. Great for entry/stop placement.",
  "Day 58: An inside bar shows consolidation. A breakout from an inside bar gives clear risk levels.",
  "Day 59: The NR7 bar (narrowest range of last 7 days) often precedes explosive directional moves.",
  "Day 60: By day 60, you should have 60 trade journal entries. Review the full set. Patterns will emerge.",
  // RISK & PSYCHOLOGY (Days 61-90)
  "Day 61: Your trading account is your tool. Protect it like a professional protects their equipment.",
  "Day 62: Revenge trading (doubling down after a loss) is how traders blow accounts. Never do it.",
  "Day 63: FOMO (Fear of Missing Out) is a signal to STOP and wait, not to enter recklessly.",
  "Day 64: The best trade is sometimes no trade. Cash is a position.",
  "Day 65: Define your max daily loss limit. When hit, close the platform. No exceptions.",
  "Day 66: The market will always be there tomorrow. A blown account will not.",
  "Day 67: Confidence is built from a tested edge, not from recent wins. Keep your process consistent.",
  "Day 68: Overtrading is the most common form of self-sabotage. Fewer, higher-quality setups win.",
  "Day 69: Position sizing is more important than entry price. Even a good entry in wrong size kills returns.",
  "Day 70: Scaling out of winners locks in profit. You never lose money taking profit.",
  "Day 71: Moving your stop loss further away when price moves against you is forbidden. Honor the stop.",
  "Day 72: Hope is not a strategy. If you're hoping a losing trade recovers, you've already failed.",
  "Day 73: Trading when tired, sick, or emotionally compromised leads to preventable losses.",
  "Day 74: The pre-market routine matters. News, levels, bias — set them before the open.",
  "Day 75: A morning routine that does not include a trading plan is a gambling routine.",
  "Day 76: Learn to love losing trades that were well executed. Bad process with good outcome is dangerous.",
  "Day 77: Good process with a loss is still a success. Repeat the good process 1000 times.",
  "Day 78: The psychological impact of a loss is 2x stronger than the pleasure of an equivalent win.",
  "Day 79: Never add to a losing position unless it was part of your original plan.",
  "Day 80: Your personality type affects your trading style. Scalpers vs swing traders. Know yourself.",
  "Day 81: Meditation and controlled breathing reduce cortisol. This improves trading decision quality.",
  "Day 82: Mark Minervini's SEPA method: Specific Entry Point Analysis. High quality entries only.",
  "Day 83: Paul Tudor Jones: 'The most important thing is money management.' He was right.",
  "Day 84: George Soros: 'It doesn't matter if you're right or wrong. It matters how much you make when right.'",
  "Day 85: Ed Seykota: 'Win or lose, everybody gets what they want from the market.'",
  "Day 86: Jesse Livermore: 'The big money is made in the big swing.' Wait for the major move.",
  "Day 87: Nicolas Darvas made $2M by trading box breakouts. Simplicity with discipline beats complexity.",
  "Day 88: Emotions are data, not directives. Acknowledge the feeling, then execute the plan.",
  "Day 89: After three consecutive losses, take a break. The market may not suit your style today.",
  "Day 90: Quarter review: How is your win rate? Average win vs average loss? Sharpe ratio? Assess now.",
];

export function getDailyLesson(): string {
  const startYear = new Date(new Date().getFullYear(), 0, 0);
  const diff = new Date().getTime() - startYear.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return TRADING_CURRICULUM[dayOfYear % TRADING_CURRICULUM.length];
}
